# Generated by Django 4.2.7 on 2025-08-29 06:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DMSDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Document reference", max_length=255),
                ),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "company_id",
                    models.CharField(help_text="Multi-company support", max_length=100),
                ),
                (
                    "solution_db",
                    models.CharField(
                        blank=True,
                        help_text="Solution-specific database for isolation (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "dms_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DMSDocumentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this approval step"
                    ),
                ),
                ("sequence", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Approval",
                "verbose_name_plural": "Document Approvals",
                "db_table": "dms_document_approval",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="DMSDocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this tag"),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=1,
                        help_text="Tag color (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document Tag",
                "verbose_name_plural": "Document Tags",
                "db_table": "dms_document_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DMSDocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this document type"
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "allowed_extensions",
                    models.CharField(
                        default="pdf,doc,docx,xls,xlsx,jpg,png",
                        help_text="Comma-separated list of allowed file extensions",
                        max_length=500,
                    ),
                ),
                (
                    "max_file_size",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum file size in MB",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "db_table": "dms_document_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DMSFileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file", upload_to="dms/documents/%Y/%m/%d/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the file attachment"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        help_text="File size in bytes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "checksum",
                    models.CharField(help_text="SHA-256 checksum", max_length=64),
                ),
                ("company_id", models.CharField(max_length=100)),
                (
                    "solution_db",
                    models.CharField(
                        blank=True,
                        help_text="Solution-specific database for isolation (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File Attachment",
                "verbose_name_plural": "File Attachments",
                "db_table": "dms_file_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DMSDocumentWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the workflow"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("workflow_data", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_workflow",
                        to="fbs_dms.dmsdocumentapproval",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="fbs_dms.dmsdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Workflow",
                "verbose_name_plural": "Document Workflows",
                "db_table": "dms_document_workflow",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DMSDocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this category"
                    ),
                ),
                ("sequence", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="fbs_dms.dmsdocumentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "db_table": "dms_document_category",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.AddField(
            model_name="dmsdocumentapproval",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_steps",
                to="fbs_dms.dmsdocumentworkflow",
            ),
        ),
        migrations.AddField(
            model_name="dmsdocument",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="fbs_dms.dmsfileattachment",
            ),
        ),
        migrations.AddField(
            model_name="dmsdocument",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="fbs_dms.dmsdocumentcategory",
            ),
        ),
        migrations.AddField(
            model_name="dmsdocument",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dmsdocument",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="fbs_dms.dmsdocumenttype",
            ),
        ),
        migrations.AddField(
            model_name="dmsdocument",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="fbs_dms.dmsdocumenttag"
            ),
        ),
        migrations.AddIndex(
            model_name="dmsfileattachment",
            index=models.Index(
                fields=["company_id", "created_at"],
                name="dms_file_at_company_937e37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmsfileattachment",
            index=models.Index(
                fields=["company_id", "solution_db"],
                name="dms_file_at_company_ffd5ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmsfileattachment",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="dms_file_at_uploade_e5fb4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmsfileattachment",
            index=models.Index(
                fields=["mime_type"], name="dms_file_at_mime_ty_5f300d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dmsdocumentcategory",
            unique_together={("name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="dmsdocumentapproval",
            unique_together={("workflow", "sequence")},
        ),
        migrations.AddIndex(
            model_name="dmsdocument",
            index=models.Index(
                fields=["company_id", "state"], name="dms_documen_company_dcac5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmsdocument",
            index=models.Index(
                fields=["company_id", "created_at"],
                name="dms_documen_company_8db909_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmsdocument",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="dms_documen_created_2c7955_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmsdocument",
            index=models.Index(
                fields=["document_type", "category"],
                name="dms_documen_documen_28f47f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmsdocument",
            index=models.Index(
                fields=["expiry_date"], name="dms_documen_expiry__17124c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmsdocument",
            index=models.Index(
                fields=["solution_db", "company_id"],
                name="dms_documen_solutio_ecfba9_idx",
            ),
        ),
    ]
