"""
Django settings for fayvad_core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from .settings import *

# Core foundation modules (scaffolded for refactor)
# Note: These are imported only when needed to avoid circular imports
# from . import entities
# from . import generation
# from . import workflows
# from . import extensions
# from . import patterns
# from . import context
# from . import services
# from . import auth
# from . import tenants
# from . import monitoring
# from . import middleware
