# Generated by Django 4.2.7 on 2025-07-31 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fayvad_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('on_create', 'On Record Creation'), ('on_update', 'On Record Update'), ('on_delete', 'On Record Deletion'), ('on_state_change', 'On State Change'), ('manual', 'Manual Trigger'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], max_length=50)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict)),
                ('workflow_steps', models.JSONField(default=list)),
                ('states', models.JSONField(default=dict)),
                ('initial_state', models.CharField(default='draft', max_length=100)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_roles', models.JSONField(blank=True, default=list)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, max_length=255)),
                ('schedule_interval', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fayvad_core.odoodatabase')),
            ],
            options={
                'db_table': 'fbs_workflow_definitions',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('odoo_record_id', models.IntegerField()),
                ('odoo_model_name', models.CharField(max_length=255)),
                ('current_state', models.CharField(max_length=100)),
                ('workflow_data', models.JSONField(default=dict)),
                ('context_data', models.JSONField(default=dict)),
                ('current_step', models.IntegerField(default=0)),
                ('completed_steps', models.JSONField(default=list)),
                ('failed_steps', models.JSONField(default=list)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('approval_history', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='running', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_executed_at', models.DateTimeField(auto_now=True)),
                ('current_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fayvad_core.odoodatabase')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fayvad_core.workflowdefinition')),
            ],
            options={
                'db_table': 'fbs_workflow_instances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255)),
                ('step_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fayvad_core.workflowinstance')),
            ],
            options={
                'db_table': 'fbs_workflow_execution_logs',
            },
        ),
        migrations.CreateModel(
            name='FBSSolutionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('database_user', models.CharField(max_length=100)),
                ('database_password', models.CharField(max_length=255)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_solution_schemas',
                'indexes': [models.Index(fields=['solution_name', 'is_active'], name='fbs_solutio_solutio_0de67f_idx'), models.Index(fields=['database_name'], name='fbs_solutio_databas_5db7dc_idx')],
                'unique_together': {('solution_name', 'database_name')},
            },
        ),
        migrations.CreateModel(
            name='FBSSchemaMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('migration_type', models.CharField(choices=[('create', 'Create'), ('alter', 'Alter'), ('drop', 'Drop')], max_length=50)),
                ('old_schema', models.JSONField(blank=True, null=True)),
                ('new_schema', models.JSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'fbs_schema_migrations',
                'indexes': [models.Index(fields=['solution_name', 'table_name'], name='fbs_schema__solutio_3c3906_idx'), models.Index(fields=['migration_type', 'status'], name='fbs_schema__migrati_3f4a84_idx'), models.Index(fields=['executed_at'], name='fbs_schema__execute_0681ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='FBSDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_type', models.CharField(choices=[('model', 'Model'), ('workflow', 'Workflow'), ('bi_feature', 'BI Feature')], max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('schema_definition', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fbs_discoveries',
                'indexes': [models.Index(fields=['domain', 'discovery_type', 'is_active'], name='fbs_discove_domain_1dcd7e_idx'), models.Index(fields=['discovery_type', 'is_active'], name='fbs_discove_discove_bee468_idx'), models.Index(fields=['discovered_at'], name='fbs_discove_discove_30ff68_idx')],
                'unique_together': {('discovery_type', 'domain', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required_roles', models.JSONField(blank=True, default=list)),
                ('requires_approval', models.BooleanField(default=False)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info')], default='primary', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fayvad_core.workflowdefinition')),
            ],
            options={
                'db_table': 'fbs_workflow_transitions',
                'ordering': ['order'],
                'unique_together': {('workflow_definition', 'from_state', 'to_state')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['odoo_model_name', 'odoo_record_id', 'database'], name='fbs_workflo_odoo_mo_f457b0_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'current_state'], name='fbs_workflo_status_b5c9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['current_assignee', 'status'], name='fbs_workflo_current_20fdb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together={('workflow_definition', 'odoo_record_id', 'odoo_model_name', 'database')},
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['workflow_instance', 'executed_at'], name='fbs_workflo_workflo_8ef384_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['status', 'executed_at'], name='fbs_workflo_status_7c2580_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['model_name', 'database', 'active'], name='fbs_workflo_model_n_93a40a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['trigger_type', 'active'], name='fbs_workflo_trigger_35d291_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('name', 'model_name', 'database')},
        ),
    ]
