# Generated by Django 4.2.7 on 2025-07-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fayvad_core', '0002_workflowdefinition_workflowinstance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FBSDiscovery',
        ),
        migrations.DeleteModel(
            name='FBSSchemaMigration',
        ),
        migrations.DeleteModel(
            name='FBSSolutionSchema',
        ),
    ]
