# Generated by Django 4.2.7 on 2025-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fayvad_core', '0003_delete_fbsdiscovery_delete_fbsschemamigration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBSSolutionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('database_user', models.CharField(max_length=100)),
                ('database_password', models.CharField(max_length=255)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_solution_schemas',
                'indexes': [models.Index(fields=['solution_name', 'is_active'], name='fbs_solutio_solutio_0de67f_idx'), models.Index(fields=['database_name'], name='fbs_solutio_databas_5db7dc_idx')],
                'unique_together': {('solution_name', 'database_name')},
            },
        ),
        migrations.CreateModel(
            name='FBSSchemaMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('migration_type', models.CharField(choices=[('create', 'Create'), ('alter', 'Alter'), ('drop', 'Drop')], max_length=50)),
                ('old_schema', models.JSONField(blank=True, null=True)),
                ('new_schema', models.JSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'fbs_schema_migrations',
                'indexes': [models.Index(fields=['solution_name', 'table_name'], name='fbs_schema__solutio_3c3906_idx'), models.Index(fields=['migration_type', 'status'], name='fbs_schema__migrati_3f4a84_idx'), models.Index(fields=['executed_at'], name='fbs_schema__execute_0681ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='FBSDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_type', models.CharField(choices=[('model', 'Model'), ('workflow', 'Workflow'), ('bi_feature', 'BI Feature')], max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('schema_definition', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fbs_discoveries',
                'indexes': [models.Index(fields=['domain', 'discovery_type', 'is_active'], name='fbs_discove_domain_1dcd7e_idx'), models.Index(fields=['discovery_type', 'is_active'], name='fbs_discove_discove_bee468_idx'), models.Index(fields=['discovered_at'], name='fbs_discove_discove_30ff68_idx')],
                'unique_together': {('discovery_type', 'domain', 'name', 'version')},
            },
        ),
    ]
