# Generated by Django 4.2.7 on 2025-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fayvad_core', '0004_fbssolutionschema_fbsschemamigration_fbsdiscovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbssolutionschema',
            name='business_prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fbssolutionschema',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fbssolutionschema',
            name='schema_definition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbssolutionschema',
            name='table_prefix',
            field=models.CharField(default='fbs_', max_length=50),
        ),
    ]
